### ISSUE TITLE
Where this file babylonjs.d.ts was found?

### ISSUE THREAD

**Issue by yuripourre** [jsweet-candies/candy-babylonjs#1]
I am trying to recreate this candy but had no success so far.

[This file](https://github.com/jsweet-candies/candy-babylonjs/blob/master/babylonjs.d.ts) seems a generated (hand-made) version. The [typescript versions](https://raw.githubusercontent.com/BabylonJS/Babylon.js/master/dist/babylon.d.ts) available are very different from this one.

**Comment by yuripourre** [comment]
Nevermind, found it here: https://github.com/BabylonJS/Extensions/blob/master/ManipulationHelpers/typings/babylon.d.ts

**Comment by lgrignon** [comment]
Hello @yuripourre 
That would be a very nice contribution.
I recommend you to start with JSweet 3 (you can find it as a branch on the main repo) which is still under preparation but should be ready for the beginning of 2020.

Anyway, could you submit here a PR when your candy is ready? I will be glad to merge it!

Thanks

**Comment by yuripourre** [comment]
@lgrignon sure, I could produce Java classes with older versions of babylon but the newer versions produces lots of errors (the typescript parser can not handle some cases apparently).
That might take a while until I have free time to spend with it again but I will certainly update you.

I also filled [an issue](https://github.com/microsoft/dts-gen/issues/147) to dts-gen hoping that it can generate a more friendly output.

Edit: JSweet3.0 (candy-generator) produces the same errors.

**Comment by lgrignon** [comment]
Sure, please let me know if you find time, we could try to make the candy generator working with latest TS defs with your help, that would be shiny.

Bye
